### ISSUE TITLE
info Training Complete. Check the outputs folder for the LoRA files.  The fluxgym program didn't run for 1 minute, and the process ended. I don't know where the problem is. Please help me take a look.

### ISSUE THREAD

**Issue by wxiaosi** [cocktailpeanut/fluxgym#247]
[2024-11-19 20:28:11] [INFO] Running E:\fluxgym\outputs\glass-lora\train.bat
[2024-11-19 20:28:11] [INFO] 
[2024-11-19 20:28:11] [INFO] E:\fluxgym>accelerate launch   --mixed_precision bf16   --num_cpu_threads_per_process 1   sd-scripts/flux_train_network.py   --pretrained_model_name_or_path "E:\fluxgym\models\unet\flux1-schnell.safetensors"   --clip_l "E:\fluxgym\models\clip\clip_l.safetensors"   --t5xxl "E:\fluxgym\models\clip\t5xxl_fp16.safetensors"   --ae "E:\fluxgym\models\vae\ae.sft"   --cache_latents_to_disk   --save_model_as safetensors   --sdpa --persistent_data_loader_workers   --max_data_loader_n_workers 2   --seed 42   --gradient_checkpointing   --mixed_precision bf16   --save_precision bf16   --network_module networks.lora_flux   --network_dim 4   --optimizer_type adafactor   --optimizer_args "relative_step=False" "scale_parameter=False" "warmup_init=False"   --lr_scheduler constant_with_warmup   --max_grad_norm 0.0 --sample_prompts="E:\fluxgym\outputs\glass-lora\sample_prompts.txt" --sample_every_n_steps="200"   --learning_rate 8e-4   --cache_text_encoder_outputs   --cache_text_encoder_outputs_to_disk   --fp8_base   --highvram   --max_train_epochs 16   --save_every_n_epochs 4   --dataset_config "E:\fluxgym\outputs\glass-lora\dataset.toml"   --output_dir "E:\fluxgym\outputs\glass-lora"   --output_name glass-lora   --timestep_sampling shift   --discrete_flow_shift 3.1582   --model_prediction_type raw   --guidance_scale 1   --loss_type l2
[2024-11-19 20:28:15] [INFO] The following values were not passed to `accelerate launch` and had defaults used instead:
[2024-11-19 20:28:15] [INFO] `--num_processes` was set to a value of `1`
[2024-11-19 20:28:15] [INFO] `--num_machines` was set to a value of `1`
[2024-11-19 20:28:15] [INFO] `--dynamo_backend` was set to a value of `'no'`
[2024-11-19 20:28:15] [INFO] To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2024-11-19 20:28:17] [INFO] 2024-11-19 20:28:17 INFO     highvram is enabled /           train_util.py:4190
[2024-11-19 20:28:17] [INFO] highvramが有効です
[2024-11-19 20:28:17] [INFO] WARNING  cache_latents_to_disk is        train_util.py:4207
[2024-11-19 20:28:17] [INFO] enabled, so cache_latents is
[2024-11-19 20:28:17] [INFO] also enabled /
[2024-11-19 20:28:17] [INFO] cache_latents_to_diskが有効なた
[2024-11-19 20:28:17] [INFO] め、cache_latentsを有効にします
[2024-11-19 20:28:17] [INFO] 2024-11-19 20:28:17 INFO     Checking the state dict:          flux_utils.py:43
[2024-11-19 20:28:17] [INFO] Diffusers or BFL, dev or schnell
[2024-11-19 20:28:17] [INFO] INFO     t5xxl_max_token_length:  flux_train_network.py:141
[2024-11-19 20:28:17] [INFO] 256
[2024-11-19 20:28:19] [INFO] E:\Python\python-3.12.7\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
[2024-11-19 20:28:19] [INFO] warnings.warn(
[2024-11-19 20:28:19] [INFO] You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
[2024-11-19 20:28:19] [INFO] 2024-11-19 20:28:19 INFO     Loading dataset config from   train_network.py:314
[2024-11-19 20:28:19] [INFO] E:\fluxgym\outputs\glass-lora
[2024-11-19 20:28:19] [INFO] \dataset.toml
[2024-11-19 20:28:19] [INFO] INFO     prepare images.                 train_util.py:1971
[2024-11-19 20:28:19] [INFO] INFO     get image size from name of     train_util.py:1886
[2024-11-19 20:28:19] [INFO] cache files
[2024-11-19 20:28:19] [INFO] 0%|          | 0/10 [00:00<?, ?it/s]
100%|██████████| 10/10 [00:00<?, ?it/s]
[2024-11-19 20:28:19] [INFO] INFO     set image size from cache       train_util.py:1916
[2024-11-19 20:28:19] [INFO] files: 0/10
[2024-11-19 20:28:19] [INFO] INFO     found directory                 train_util.py:1918
[2024-11-19 20:28:19] [INFO] E:\fluxgym\datasets\glass-lora
[2024-11-19 20:28:19] [INFO] contains 10 image files
[2024-11-19 20:28:19] [INFO] read caption:   0%|          | 0/10 [00:00<?, ?it/s]
read caption: 100%|██████████| 10/10 [00:00<00:00, 10034.22it/s]
[2024-11-19 20:28:19] [INFO] INFO     100 train images with           train_util.py:2012
[2024-11-19 20:28:19] [INFO] repeating.
[2024-11-19 20:28:19] [INFO] INFO     0 reg images.                   train_util.py:2015
[2024-11-19 20:28:19] [INFO] WARNING  no regularization images /      train_util.py:2020
[2024-11-19 20:28:19] [INFO] 正則化画像が見つかりませんでし
[2024-11-19 20:28:19] [INFO] た
[2024-11-19 20:28:19] [INFO] INFO     [Dataset 0]                     config_util.py:567
[2024-11-19 20:28:19] [INFO] batch_size: 1
[2024-11-19 20:28:19] [INFO] resolution: (512, 512)
[2024-11-19 20:28:19] [INFO] enable_bucket: False
[2024-11-19 20:28:19] [INFO] network_multiplier: 1.0
[2024-11-19 20:28:19] [INFO] 
[2024-11-19 20:28:19] [INFO] [Subset 0 of Dataset 0]
[2024-11-19 20:28:19] [INFO] image_dir:
[2024-11-19 20:28:19] [INFO] "E:\fluxgym\datasets\glass-lora
[2024-11-19 20:28:19] [INFO] "
[2024-11-19 20:28:19] [INFO] image_count: 10
[2024-11-19 20:28:19] [INFO] num_repeats: 10
[2024-11-19 20:28:19] [INFO] shuffle_caption: False
[2024-11-19 20:28:19] [INFO] keep_tokens: 1
[2024-11-19 20:28:19] [INFO] keep_tokens_separator:
[2024-11-19 20:28:19] [INFO] caption_separator: ,
[2024-11-19 20:28:19] [INFO] secondary_separator: None
[2024-11-19 20:28:19] [INFO] enable_wildcard: False
[2024-11-19 20:28:19] [INFO] caption_dropout_rate: 0.0
[2024-11-19 20:28:19] [INFO] caption_dropout_every_n_epo
[2024-11-19 20:28:19] [INFO] chs: 0
[2024-11-19 20:28:19] [INFO] caption_tag_dropout_rate:
[2024-11-19 20:28:19] [INFO] 0.0
[2024-11-19 20:28:19] [INFO] caption_prefix: None
[2024-11-19 20:28:19] [INFO] caption_suffix: None
[2024-11-19 20:28:19] [INFO] color_aug: False
[2024-11-19 20:28:19] [INFO] flip_aug: False
[2024-11-19 20:28:19] [INFO] face_crop_aug_range: None
[2024-11-19 20:28:19] [INFO] random_crop: False
[2024-11-19 20:28:19] [INFO] token_warmup_min: 1
[2024-11-19 20:28:19] [INFO] token_warmup_step: 0
[2024-11-19 20:28:19] [INFO] alpha_mask: False
[2024-11-19 20:28:19] [INFO] custom_attributes: {}
[2024-11-19 20:28:19] [INFO] is_reg: False
[2024-11-19 20:28:19] [INFO] class_tokens: cgmi,
[2024-11-19 20:28:19] [INFO] caption_extension: .txt
[2024-11-19 20:28:19] [INFO] 
[2024-11-19 20:28:19] [INFO] 
[2024-11-19 20:28:19] [INFO] INFO     [Dataset 0]                     config_util.py:573
[2024-11-19 20:28:19] [INFO] INFO     loading image sizes.             train_util.py:923
[2024-11-19 20:28:19] [INFO] 0%|          | 0/10 [00:00<?, ?it/s]
100%|██████████| 10/10 [00:00<00:00, 10034.22it/s]
[2024-11-19 20:28:19] [INFO] INFO     prepare dataset                  train_util.py:948
[2024-11-19 20:28:19] [INFO] INFO     preparing accelerator         train_network.py:379
[2024-11-19 20:28:19] [INFO] accelerator device: cuda
[2024-11-19 20:28:19] [INFO] INFO     Checking the state dict:          flux_utils.py:43
[2024-11-19 20:28:19] [INFO] Diffusers or BFL, dev or schnell
[2024-11-19 20:28:19] [INFO] INFO     Building Flux model schnell from flux_utils.py:101
[2024-11-19 20:28:19] [INFO] BFL checkpoint
[2024-11-19 20:28:19] [INFO] INFO     Loading state dict from          flux_utils.py:118
[2024-11-19 20:28:19] [INFO] E:\fluxgym\models\unet\flux1-sch
[2024-11-19 20:28:19] [INFO] nell.safetensors
[2024-11-19 20:28:19] [INFO] INFO     Loaded Flux: <All keys matched   flux_utils.py:137
[2024-11-19 20:28:19] [INFO] successfully>
[2024-11-19 20:28:19] [INFO] INFO     Cast FLUX model to fp8.   flux_train_network.py:92
[2024-11-19 20:28:19] [INFO] This may take a while.
[2024-11-19 20:28:19] [INFO] You can reduce the time
[2024-11-19 20:28:19] [INFO] by using fp8 checkpoint.
[2024-11-19 20:28:19] [INFO] /
[2024-11-19 20:28:19] [INFO] FLUXモデルをfp8に変換して
[2024-11-19 20:28:19] [INFO] います。これには時間がか
[2024-11-19 20:28:19] [INFO] かる場合があります。fp8チ
[2024-11-19 20:28:19] [INFO] ェックポイントを使用する
[2024-11-19 20:28:19] [INFO] ことで時間を短縮できます
[2024-11-19 20:28:19] [INFO] 。
[2024-11-19 20:29:13] [INFO] Traceback (most recent call last):
[2024-11-19 20:29:13] [INFO] File "<frozen runpy>", line 198, in _run_module_as_main
[2024-11-19 20:29:13] [INFO] File "<frozen runpy>", line 88, in _run_code
[2024-11-19 20:29:13] [INFO] File "E:\Python\python-3.12.7\Scripts\accelerate.exe\__main__.py", line 7, in <module>
[2024-11-19 20:29:13] [INFO] File "E:\Python\python-3.12.7\Lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
[2024-11-19 20:29:13] [INFO] args.func(args)
[2024-11-19 20:29:13] [INFO] File "E:\Python\python-3.12.7\Lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
[2024-11-19 20:29:13] [INFO] simple_launcher(args)
[2024-11-19 20:29:13] [INFO] File "E:\Python\python-3.12.7\Lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
[2024-11-19 20:29:13] [INFO] raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
[2024-11-19 20:29:13] [INFO] subprocess.CalledProcessError: Command '['E:\\Python\\python-3.12.7\\python.exe', 'sd-scripts/flux_train_network.py', '--pretrained_model_name_or_path', 'E:\\fluxgym\\models\\unet\\flux1-schnell.safetensors', '--clip_l', 'E:\\fluxgym\\models\\clip\\clip_l.safetensors', '--t5xxl', 'E:\\fluxgym\\models\\clip\\t5xxl_fp16.safetensors', '--ae', 'E:\\fluxgym\\models\\vae\\ae.sft', '--cache_latents_to_disk', '--save_model_as', 'safetensors', '--sdpa', '--persistent_data_loader_workers', '--max_data_loader_n_workers', '2', '--seed', '42', '--gradient_checkpointing', '--mixed_precision', 'bf16', '--save_precision', 'bf16', '--network_module', 'networks.lora_flux', '--network_dim', '4', '--optimizer_type', 'adafactor', '--optimizer_args', 'relative_step=False', 'scale_parameter=False', 'warmup_init=False', '--lr_scheduler', 'constant_with_warmup', '--max_grad_norm', '0.0', '--sample_prompts=E:\\fluxgym\\outputs\\glass-lora\\sample_prompts.txt', '--sample_every_n_steps=200', '--learning_rate', '8e-4', '--cache_text_encoder_outputs', '--cache_text_encoder_outputs_to_disk', '--fp8_base', '--highvram', '--max_train_epochs', '16', '--save_every_n_epochs', '4', '--dataset_config', 'E:\\fluxgym\\outputs\\glass-lora\\dataset.toml', '--output_dir', 'E:\\fluxgym\\outputs\\glass-lora', '--output_name', 'glass-lora', '--timestep_sampling', 'shift', '--discrete_flow_shift', '3.1582', '--model_prediction_type', 'raw', '--guidance_scale', '1', '--loss_type', 'l2']' returned non-zero exit status 3221225477.
[2024-11-19 20:29:13] [ERROR] Command exited with code 1
[2024-11-19 20:29:13] [INFO] Runner: <LogsViewRunner nb_logs=117 exit_code=1>

**Comment by oloboy** [comment]
How many video ram you have ? have you the driver up to date ? do you have a nvidia card?
becasue the returned non-zero exit status 3221225477 il link to some problems in gpu driver memory

**Comment by oloboy** [comment]
try to update reinstall fluxgym

**Comment by wxiaosi** [comment]
I reinstalled the system and redownloaded it several times. It's the same problem. Is it because my nvidia information can't be recognized?

**Comment by crocknroll64** [comment]
same , downgrading to studio driver 565.90 , hope it helps

**Comment by oloboy** [comment]
You use flux schenll to train lora? Use de instead.
Have you try to uninstall pinokio and python and reinstall it?

**Comment by kolaczek9** [comment]
I have exact same issue I have tried each and every thing you guys suggested yet the problem still persist. I even went one step futher with fresh install of windows then ran pinokio. Same problem even if I do it manually.

**Comment by oloboy** [comment]
try to go in fluxgym dir and run pip install -r requirements.txt
have you choise 12G in VRAM section?
![image](https://github.com/user-attachments/assets/561c2362-8359-4f4d-b007-c58774eb0b21)

**Comment by beenycool** [comment]
happens to me as well
i thought it was just a gpu issue
rtx 3060 laptop gpu 12gb vram
16gb ram

**Comment by wxiaosi** [comment]
My problem is solved. I run the program and find that the failure caused by the high memory occupation. I tried a few more times to have success. It is recommended that the memory exceed 32.

**Comment by wxiaosi** [comment]
> 尝试进入 fluxgym 目录并运行 pip install -r requirements.txt您是否在 VRAM 部分中选择了 12G？ ![image](https://private-user-images.githubusercontent.com/70330374/389201758-561c2362-8359-4f4d-b007-c58774eb0b21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NDUzNzcsIm5iZiI6MTczMjU0NTA3NywicGF0aCI6Ii83MDMzMDM3NC8zODkyMDE3NTgtNTYxYzIzNjItODM1OS00ZjRkLWIwMDctYzU4Nzc0ZWIwYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE0MzExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NTIxMDQ2ZjcwMjdjZGNiOTZkMDJmNWNjNmY2Nzc3N2VhY2QyNDdhNTM3M2YxY2MxNGUzZTA3OTBmNjU4MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NDCC41BvFvrtrdf90FIt_Xyojr8TvFH0dkx5kgMzYo0)


My problem is solved. I run the program and find that the failure caused by the high memory occupation. I tried a few more times to have success. It is recommended that the memory exceed 32g.  
Thanks for your help.

**Comment by kolaczek9** [comment]
I have resolved the issue by increasing Virtual RAM to 50gb in initial 60 seconds of running training the RAM usage gets up to 49GB , yet same as the person above now i am getting CUDA OUT OF MEMORY error, yet my 3060 has 12gb , i have tried to train on 3 images 1 step and 2 epochs, with low vram yet issue persist.

**Comment by dreamhacking** [comment]
ok, I had the same problem. I tried 2 images 1024X1024 without captions (only trigger word as caption) and it worked.
